spring:
  datasource:
    url: jdbc:mysql://localhost:3306/binder-dev
    username: root
    password: adobe1590@qq

  data:
    redis:
      host: localhost
      port: 6379
      password:
server:
  port: 8081